rm(list=ls())
library("R.utils")
modify_seq<-function(tochang){
  new=list() 
  for (l in 1:length(tochang)) {
      i=tochang[l]
      if (i=="A") new=append(new, "G") #paste(new,"G", sep="")
      if (i=="C") new=append(new, "A") #paste(new,"A", sep="")
      if (i=="G") new=append(new, "T") #paste(new,"T", sep="")
      if (i=="T") new=append(new, "C") #paste(new,"C", sep="")
      if (i=="N") new=append(new, "T") #paste(new,"T", sep="")
  }

  return(new)
}

revcompl<-function(secu) {
  seqs=as.list(strsplit(secu,""))[[1]]
  new=""
  
  for (l in seq(1,length(seqs))) {
    i=seqs[l]
    if (i=="A") new=paste(new,"T", sep="")
    if (i=="C") new=paste(new,"G", sep="")
    if (i=="G") new=paste(new,"C", sep="")
    if (i=="T") new=paste(new,"A", sep="")
    if (i=="N") new=paste(new,"N", sep="")
  }
  splits <- strsplit(new, "")[[1]]
  reversed <- rev(splits)
  final_result <- paste(reversed, collapse = "")
  return(final_result)
}

shotreads<-function(seqc,size) {
  reads=list()
  secuen=as.list(strsplit(seqc,""))[[1]]
  cat("Sequence size:",length(secuen), "\n", file="Create_reads.log", append = TRUE)
  cat("Read size:", size, "\n", file="Create_reads.log", append = TRUE)
  for (s in seq(1,length(secuen)-size+1)) {
    newseq=secuen[seq(s,s+size-1)]
    read=""
    for(n in newseq) { read=paste(read,n,sep="") }
    reads[s]=read
  }
  return(reads)
}

modify_genome_inblocks<-function(mys,pi,ecarts){

  secuen=as.list(strsplit(mys,""))[[1]]
  sizeseq=length(secuen)
  cat("Original Sequence size:", sizeseq, "\n", file="Create_reads.log", append = TRUE)
  modiread=""
  nc=as.integer(ecarts*(100-pi)/100)
  cat("Change", nc, "nucleotides every",  ecarts, "bs \n", file="Create_reads.log", append = TRUE)
  for (e in seq(1,sizeseq-ecarts+1, ecarts)) {
    start=secuen[seq(e,e+ecarts-1-nc)]
    for (s in start) {modiread=paste(modiread,s,sep="")}
    q=secuen[seq(e+ecarts-nc,e+ecarts-1)]
    final=e+ecarts-1
    new=modify_seq(q)
    for (n in new) {modiread=paste(modiread,n,sep="")} 
  
  }  
  if (final < sizeseq) {
    end=secuen[seq(final+1,sizeseq)]
    for (f in end) {modiread=paste(modiread,f,sep="")}
  }
  return(modiread)
}

initialseq="AAATGCCCCCCAAGCTCACCAGCAACCAGCCCGAGCCGCCACCCCCGCCGGCTCCAGCACCGACGCCGCCACCGCCGCCCAAACAGCCGTCGTTGACGACATTCTTCGGTCTGCGATGAAACACCCAGCGGACGTTCGCCGCGACTTGTCCTGCGCCGACAATCGCCGCATAATTGCCTGATGAAAAAACAACCGTTCCGGCTGACGCCGTACCAAGTGCAGTGGCTGCTGATCGTCGGCTTTCTGACCGTCGGCTACGCGCTGTATCTGCGCTATCTGGCGATCGAATTCTCGACCGTGGCGCTGGCCTGCGACGCCGGGCTGCACAGCATGCTGTGCAAGACCCGGATCCTGATGACCGCGCTGTTCCAGAATTCGGTGTTCGGCATCGTGGCGGTGGTGATCGCCGTGTTGCACCTGATCCGGCCGTCGATCGTGCTGCTGACCGGCGGCCTGATCGCCGCCGGCTTCGGCATCGTGCTCTATAATGTCGGCCTGTCGGGGCTGGCCATCGGCCTGCTCATTTTGGGATTTGCACGGCCCGCGCCCGCCACAGCGTGATGCCGAGCGCCACATAGATCGCGCAGGTCCACAATGATTGCCAGTTCTTCGGCCCCTCATTGAAACCGATATAGACCGCGGCGACCAGGAACAGGCCGGCGAACGCCGCCTCGGCGATCGGACGGACGCCGTTTTGCGGACGGTTCAGCACCATCAGGCTGAACAGCGGCAGCACTGCCATCGTCAGCGCCGCGAACGGAAAATCGCGGTATCGCGGGTCGAACACGAATCCCAGCGCGGTTTCCGCCGCGATCAGGGTCGTCACCATCAGCGCCAGACCGAGCGCATAGGTCAGCACTGAGCCGCCCCTGCCCTCGCGCGGACCGATCAATTCCAGAAACGTCGGCAGCGAGCGCCCGGCCATCAGCGCGTGAGCGCCCAGCAACGGCGTCACGATCCCACTGGCCAGCAGCAGCGTCCATTGCACCCAGCCGCCCGTGGTGTAGCTCTCGTGCAGCAGCTTATCGACGGCGACGCCGAGCAGAATCCCCGACGCCGTCGCCGACAACCCCACGGCCAGCCATGACATCAGACGCGGCGACCAGGGCCGGCGCCGCAGCGTCAGCAACGCGGTCCCGAACACCAGCAGGCTGAGACCCAGCCCGCTGGCGAGCCCTAGCTTCCATTGCGGAAAATTATTGATCGGCCGCCCGGCCGGATATTTCAGCTCCCGCTTGTCGGAATTGATCAAGCCCCAATAACCGCCGACAGTGCCTTCGAGCTTGCGCTTCCACGGCTGGTCATAGGCCTCGATCAGATTGACGCGGAAATTCTCGCGCTTCGCCAGACCGAGGATTTCCGACACCACCCGCGCCTGGTTGCTGCGCGACGGCAACGCGCCCTCGCGCATCCGGCCGGCGCTCGGCCAACCGGTTTCCCCGATCAGGATTTCCTTGGCCGGAAACGCCGCCGCGATCTGCTTGCGGATCGAATCCACATGGGCGGCGGCATAGCTGGCGCGCACCGGCACGTCCTCCCAATAGGGCAGAATGTGGATGGTGACGAAATCCACCGCGTCGTAGATTTCCCGGTTGCGCAGCCAGTATTCCCAGACATCCGCATAGGTCACCGGCACGGTGACCTGCGCCTTGACCGAGCGAATCGTCGCGGCGAGATCGGCGGCGGTCATTTCGCCGCGCAGCAGCACTTCATTGCCGACCACCACCGAGGCGATCACGCCGGGATATTCCTTGGTCAGCGCCACAGCCTTGGCGATCTGCGACAGGTTCTTGAACCGGTTATTGCCGAGCCAGATTCCTTGAATCACTTTGAGACCGACGGCACCGGCCAGCTCGGGGACCTGGTCGAGGCCGTTGTCGACCGAATAAGTGCGCACGCATTTCGAGATCTTGGCCAGTTGCGCCATGTCCTCGGCGATTTGCGCCTTATCAATCTGGGTGGTCGGATCCAACGGCGTCTGGGCGGCGCGGAACGGCGCATAGGACACGCATTCCAGCTTGGCAGCCGGATCGATCGGTGCGCGCGCCAGCGTCACCGGCGTGGCGATCAGCCACCACACCGCGATGATTGTGCAAAACGATAGCAGGAGAAGCGCCAGTGGCGTGCGAAGCGAAATGGTTTTCGTCCTCCATGGAGTCCGTCGATTAGCCGGTCGTTGGCTCGCTGCCAAGGGGGCTGCCAGCGGCAGCCGAGGTTTGTCGCGGTTATCGAGGGAGCTGCCCTATGAAGGGAGCAGCCTTGGCTCAGGGAAGCAGCCTTGGCGCCGGCAAGCGCAGCCGCCGCTAATCCGGCGACCTCGTCATCATGGCACCCATCGCTTGGAGACCACCATCAACAAAACACGATTGCCTGCGCCAACTGACACAGCGCGATTGCTGGACAAAATCGTAAATGTCCGTCATGGGAATCTGAACGGATCACTGACATATTGGTGACCTATTCGAACCGCATCAGACCGGCACTGCGCCGTGACGGGCAACAATATCGGGGACATTATGCGACGACGGGTGCTCGAGTTCCAAAATGCGGCCTTGCGTTGTTTGGCCGCGCCTGGGCTGGCGCTGCTGATCGGCATCGGCGGGGCAATCGCCCAAAGCGGTGACCTTCGCGCCCAGGATCAGCCCAGCAAGCCGGCGACGAACAATAATACGGCCGCCCCGGCCGTCGATCCGCTCAAGGAAAGCCAGCGCAAGACCAACGAATTCGTCGAGGCCGCGCAGGCGATCAACGGGCCGGCCGGCAATCCCGAATGCGTCTGGCTGGGCCGGCGTGTGGTCGCGCTGATGTGGCGCGACGACCTCGACACCGCGTTCAGACACCTCAACCTTTACGACCGGTTTGGCTGCCCCGGCGGTCACGTTCAGGCGGCGTTCAGGTGCCTCGTGCGATTTGGAACAATCGACCCGAAGGCGCCGGATAGCCTGAGTGGGCGCGTTCATGCCTGCTGGATCAATCCGAATGCGCAGCCTCAAGAGGTGGCGGCCTCACCGGCTCCCTCCGGCGCAGCAAATGCGGCGCCGGCGGCGGCTCCGGCCTCACCTCCGGCGGCGAAATAGAATGGCCGCTGTGAAACGGAATTGACACGGTGCTGCTGAACACTGAAATTCGACGTGGCGGCATCTCGGCCGCTGCCGTCGAATTGCCGCAGCGGTAGTGTGAGTTTGGTCGGCCGCGGGTGTTCGGCCGATTTGTAATCCACGTGGCAGAGCGATGCTTGATTTGCCGCAGCCTTGGTCGGACCTCGGGGGCGGGTCCGCTTTCCCGCCGTGTTGGCCCTGTATGGTTTAGTCGCGATGCGCGCCGTCGTCGCCGTTCTGCTAGTCGTCGCTGCCGCTCACGCTGGCCTTTGGGGCATTTTGAGAGAGTCGCAGCAGGCTCCCGATTTCAAGGGCATCCTGCCCAGCGTGTCCTATGCGCCATTCGACGGCAGCGGCCATCCCGACGTCGATAACATCCCCAACGCCGACCGTATTCGCGCCGACATGAAGGTGCTGGCGCCGCTGACCCGCGCCATCCGGCTGTATTCGTCCACCGGCGGCGTCGAGATGGTGCCGCCGATCGCCAATGAAGTCGGGCTGAAGGTCACGGTCGGCGCCTGGATCGACAAGGACGACGATCGCAACGAACGCGAAATGCTGTCGGCGATCGATCTGGCCAAGCACAACAGCAACGTCAACGCCGTCGTGGTCGGCAACGAAACCATCTATCGCGGCGAGCAGAAGGTCGAGGACCTGATCAAGCTCATCCAGCGAGTTAAGAGCTCTGTCAATGTCCCCGTCACCACTGGCGAAATCTGGAACATCTGGCTCGATCATCCGGAATTGGCGTCGTCGGTGGATTTCATCGCCGCGCACATCCTGCCCTATTGGGAGGGGTTCTCCGACAAGAAGGCCGTGGATCAGGCGCTGATCATCTATCAGAAACTGCGCAACGCGTTTCCGGGCAAGCGCATCGTGATCGCCGAATTCGGCTGGCCGAGCGCGGGGTATAATCTGAAGAGCGCCACCCCCGGCCCGTTCGAGCAGGCGGTGACACTGCGCAATTTTGTCAATCGCGCCGAAGCGATCGGGATGGACTACAATATTGTCGAGGCGATCGATCAGCCCTGGAAGTTCTTCGAAGGCGGCGTCGGTCCCTATTGGGGTATCCTGAACGCCGCGCGCGAGCCGAAATTCGCCTGGACCGGGCCGGTCGTCGATGAGACCTATTGGAAACAGGCCGGCATCGCCTTGCTGGTCGGCATCCTCCTGTCGCTGCCGATCCTCCAACTGCTCTACCCCACGGCCATGCAGGCATTGCTGCTGTCCTCGGCGGCGCACGGCGTCGGCGCCTGGGTGGCAACCATCTTTGCCTATTGGACCGGGCATTACTTCGTGTTCGGGTCGGCCTTCGCGCTGACCCTCGGCCTGATCCTGCTGGTGCCGCTGGTTCTGATCGCGCTGGCGCGGGTCGAGGAGATCGCCGCGGTCGCGTTTGGCCGCAAGCCGCAGCGGCTGCTGGCCAAGCCCCCCGCGCCGCTGCTGCTCGCGCGAGCCTCCGGGACATCGGCCGAAACCGAGGCTGCAGCGGCCGTCAAGACGCCGAAAGTGTCGATCCACGTTCCGGCCTATTTCGAGCCGCCGGATATGCTGAAGCTGACGCTGGATGCGGTGGCACGGCTGGATTATCCGAATTTCGAATGCGTGGTGATCATCAACAACACCCCCGATCCGGAGTTCTGGCAGCCGATCCAGGATCATTGCCGCGAACTCGGCGAGCGCTTCAAATTCATCAACGCCGAAAAGGTCGAGGGCTTCAAGGCCGGCGCGCTGCGGATCGCGATGGATCGCACCGCCGCCGACGCCGAGATCATCGGGATCATCGACGCCGACTACATGGTCGAGCCGAACTGGCTGAAGGATCTGGTGCCGGCATTCGACGATCCGCGGGTCGGCCTGGTGCAGGCGCCGCAGGACCATCGCGACGGCGACCGGTCGTTGATGCATTACATCATGAACGGCGAATATGCCGGCTTCTTCGACATCGGCATGGTTCAGCGCAACGAATGCAACGCCATCATCGTGCATGGCACGATGTGCCTGATCCGCCGCGCCGCGATGGACATGGCCGGCGGCTGGGCCGGCGACACCATTTGCGAGGATAGCGATCTCGGACTCGAGATCATGGAGCACGGCTGGCTCACCCATTACACCAACCGCCGCTATGGCTATGGGCTGCTGCCCGACACCTATGAGGCGTTCAAGAAGCAGCGCCATCGCTGGGCTTACGGCGGCTTCCAGATCATCAAGAAGCATTGGCGGCGGTTTCTGCCCGGCGCCAGCCGGCTGTCGCAGGACCAGAAGCGCGAATTCGCGCTGGGCTGGCTGAACTGGCTTGGCGCCGAAAGCCTCGGCGTGGTGGTGGCGATCCTCAATCTGATCTGGGTGCCGATCGTAGCCTTCGCCGACATCGCGATTCCCGACAAGATCCTCACTTTTCCGATCATCGCTTCATTTGTGGTGTCGCTGATCCATTTCGTCGCGATGTACCGGCTGCGCGTGCCGGTGAAGATCCCGCAAATGCTGGGCGCGATGATCGCCGCGATGTCGGTGCAATGGACGGTGTCGCGTGCGGTGGCGCAGGGGCTGATCACCGAGCATCTGGCCTTCGCCCGCACCTCCAAGGGCGGTTTCTCGCTGATGTCGGTCGAGTTCCAGGCATTCTGGGAAGCGGTGATCGGCGTGCTGCTGCTGGCCGGCGCCGCGGTGCTGGTGGCCTCCAACAGCTTCAAGCAGGTCACCGAGATCTACATTTTCGCCGCGGTGCTGGTGCTGGAAAGCCTGCCATTCCTGTCGGCGGTCGCCATCGCCATCCTGGAAAATTCCCGGATCAATTCCTTCACCTTCTGGCGCAATACGAGCGTCCGCACCGCCGAGCTGATCGGGCTGCGGCGGGTGTCGCTGCCGGCCAAGATCCCCGCCCCGCAGCCGGTGGCGTCCGAGGTCCATCGCGACAAGATCAAGGTGGCCGGCTAGGGCCGCTTGTCCGGATCGACCCTGGGTTGATTGAGCGCACGAAATGTTTCGGCTAAATATCTGTGCAAATGAGCCAATCCGGCTTAAACCGGATTGCGGCACCCGCGCCCGCTATTGACCGCGGCGGGCCTGCCCCCTACACAGCGCGGCACGTGAGCGCGTAGCTCAGTCGGTAGAGCACGTGACTTTTAATCATGGGGTCGAGGGTTCGAATCCCTCCGCGCTCACCATGAATTTCCTTGCACCTCGCCTGATCGCGGACAGACCCGGCCCTTTCGGTGCGGTGCTGGCGCCAGATCCGCCATTGGGTCCAAGCCGCAGGCGCCAGTCGGCCGCATGCCGGGAAACCTATTGGCCGAGCCCGCAGCGCTGGCCGTCCATGCCCCGACCGGCGATTCTTCCGCCATGTACCAAAAGAGAGACAAGCAAACGGGCGAACCCGCTTAGGCTGCTCGCATAGATTGATTCGTTCACAAGCACGCCACCGAGGACATGCAATGAGCAGATTCCTGATCGGCAGTTTTGGCGCCCTTGCGCTGGTGACCTCGGCCGCCGCAGCCGACGTCGCCCCCTACGCCAAGGCTGCGCTGAGCGCACCGGTATATCGGTGGAGCGGTTTCTATCTGGGCGCCAATGGCGGCTGGGGGACCAGCCAGAAGTGCTGGGATTTCGTCAATACGGCCGGAACCTTCCTGGTCTCGGAAGGCTGCCACAATGCCAGCGGCGGCACTGCCGGCGGCCAGCTCGGCTATCGCTGGCAGGCCGCCAACCTGGTGTTCGGCATCGAAGCCCAGGGCAACTGGGCGGATTTCAACGGCAGCAACCAAAGCGTGCCGTTTCCGGCCGTCGTCAATGCCACCCGCGTCGAATCCTTCGGCACTTTCACCGGCCAGATCGGCAATGCCTGGGGCAACACCCTGCTCTACATCAAGGCCGGCGGCGCGGTAACCAACGATCGCTATCTGGGATACCTCACGGCGACCGGGACGCAGATCAGCGATACCGTGACGGACAATCGCTGGGGCGCCGTGGTCGGGGTCGGCCTGGAATATGGCTTTGCCGCAAACTGGTCGGTCGGCGTCGCCTATGATCACATGTTCATGCAGGACCGCCTGATCACCTTCACCAATGTCGGCACAGTCAAACCCTCCGGCGCCGCCTTTGCGAGCGACCGCATCCATCAGGACGTCGATCTGGTCACTATGCGGCTCAACTACCGCTGGGGCGGCTAATCGGTGTCACCGGGCGGTCCTGCGATCAATCCGGACGATAACCGGCAAGGTTACGCACGCAGGTAACTGACTGTGGACGCGGGTCCCCTGCCAGTGTTAGCGTCAAACCTGCCTTTTTGCCTGTTCATCCGCGGCTCTCTCGGCAGCGGCGTCAGCAAAGCCCATTCTCGCTGTCGAACAGGAATATCATGCGCATCACCCTGGTCGGCTCTCGCCATTTCGGAGCGACAACCCTCACCATGCTGCGCCAGCATGGCATCGACATCGTCAGGGTCGTGGTCACCGATCCCGAGGACCGGCTTGCCGTTGCGGCGCGGGCCGCCGGCGTCGAGGTGACGGTCCAGGCCAACCCGAAGCGCGTGGAGGCCTCGGAAATCGCCTCCGATACCGATCTGATCGTGACCGCCCACAGCCATGCAAGGATCAGCCGCGGCGCCTTGGCGGCCGCCCGGCTCGGCGGCATCGGCTATCACCCCTCACTGCTGCCACGTCACCGCGGCATCGCCGCGGTGGAATGGACCATCCGCGAAGGCGATCCGGTCACCGGCGGCACGATCTATCATCTGGCCGACCAGATGGACGCCGGCGCGATCGCCGCCCAGGAATGGTGCTTCGTCAAGAAGGGCGAAACCGCCCGCGAATTATGGGAGCGCGCCCTCGCTCCGCTCGGTCAGAAATTGCTGGCCCAGGTGATCGATTCGGCGAAGGAAAATGGCGAACTGCCGGCCCAGCCGCAGGATGAGCAATTCGCCACCAATGCGCCGAAACTGGCGGATTGAGCCGCAGCGCTAAGCCAATAAAGGAAATTTATGGAACATTGTCGATGGTAGCCCGTTGACACCGAGAGATATTTTGCTGCATTGCAACAAACTTCACACAGCAGACTTCGCATATCAGGGCGCCTTGTCGGGTGCCCATCCAATTCAGGGGATTTAATTGATGCGCTTGAACAGCCTTCGTCTGCTCGTCGCTTCCGTCGCGGCGGCTGGGATTCCGGTCGGTTCCGCGATGGCGGAGACGGCATTTGACGGGTTGTGGACAGTGACGGTCATTACCAAGGCCGGCAGCTGCGAGCCGTCGGCGCGCTATCCGCTGACGGTGACGGACGGCAAGATCACGGCGTCGGACGCCGAGGTCTCCGGCCGGGTCGGCCGCGCCGGCAACGTCCGGGTTACGATTCGCGGAACCTACGCGAATGGTCAGCTCAGCGGCAACACCGGGGCCGGCAAGTGGAACGGCGCCTCCGGCGGCATCCCCTGCAGCGGACGCTGGGAAGCCTCCCGCCAGTGATGGCCCTGCCCGGCGCGCGACCTGCGTCCAGCCGATTGGATCAGGATTTCTTCGGTTCGACCAACTGAGCCGCGGTCTGCTTGATGGTCTTGGCGATCAGCAGCGCCTGCTCCTTGTTGAAGGCGAAATCCTGAACGCCCTCATGAGTGGTCAGCGACAGCACCATCAGGTCGGGCTGGGCTTCGGGCCAGCCGGTGGCGAAGGCGGTGACGAAATTGGCCGAAGTGGATCGCTGCGTCATCGATGACATCCTTGCAATTGGTCGCCGGCTTGTTGGACCAAAGCCACCAGCGCCGCAAGGCCGGCTCTCCCGCATCGCATCAAATTGACCTCCGGAATTCGCTCAAGCCGTCCCGCCGCGGCGGTTGCCAAGCCGGTCGATCTCGCAGATAGAGCCTGTGAGCCCGTCTTGGCGCGTTCCGCGCTGTCACCCCTCACAGCGCGTTGCCATGACCCGAAAGCCTTCCACCACCAGGGCTGCGCTATGGATGGCAGGGTGGCTCACGCTGATGTTGATCGTGGCGATCGCCGGCCGCGAGACCACGCGCGAGCTGAACGTGTTCCAGATCATGGAACTGCGCTCCACCATCGGCTTCGTCATGCTATATCCGCTGGTTCATGCCGCCGGCGGCTTTGCCGCGATGCGGTCGGCGCGCGGCGCCCATCATGTCGCGCGCAATATCGTGCATTATGCGGCGCAGAGCTGCTGGTTCTTCGCGCTGACGATGATTCCCCTGGGCCAGGTGGTGTCGATCGAATTCACCATGCCGATCTGGATCGCGATCCTGGCGGTGACGTTCCTCGGCGAACATATGACCTTCTGGAAGGTCTGCGCGATCATACTCGGCCTGATCGGCGTGGTGGTGATCGTGCGTCCCGAAACCGGCACGGTCAATCCGGGACAGTTGATCGCGCTGGCCGGCGCCGTCGGCTTCGGCATTTCCATCACCTTGGTCAAATCGCTGACCCGGACCGACACCACGCTGACGATCATCTTCTGGATGCTGGTGATCCAGTCGGTCATCGGCTTCGCCCCGGCGCTGTATTTCTGGCACTGGCCGAGCGCCTATGCCTGGGGCTGGATCGTGGTGATCGCGTTCTGCGGCACCTTCTCGCATTACTGCATGGCGCGGGCGATGCTCTATGCCGATGCCACCGTGGTGGTGCCGATGGACTTCCTGCGGGTGCCGCTGACCGCCACCGCCGGCTGGCTGCTCTATGCCGAGCGGATCGATCTTTACACCGCGCTCGGCGCGGTGCTGATCCTGTCGGGCAATCTGCTGAACCTGAAGCGCGTGACGCCGGCCCGCACAGCAAGCTGAGCGCGGGCTACGACAGCCCTGCCGCCTTGCGCAGCGCCGCGTTGATCCGGTCCTGCCAGCCGGGGCCGTCCTCCTGGAAATGCTCCAGCACGTCCTGATCGATCCGCAGCGACACCTGCTCCTTGATGCCGGGGATCGCGGTCGGCTTCGGCGGCGCCTCGGGCTCCTTGGTGGTGGCTTTCTTGAACACGGCTTCGGCCTCGGTGCGGGCATCGTTCAGAGTACGCGGGCGGCGCGGCGGTTGGGACATGGATCTCTCTCAAGCAAGGGTGAAACGTCGGACTGAAACCGCAGACGTCCTGGCGCGGCCCCTCGACAGTGTGCGCTGCGGCAGGACGTCACGATTTCGCGACCTTCTATCATGCCGCGCCGCGCTCGTCGTGTTCGCATCGCACCATCAACGGTGCTGGCGAAACAAAGGCACGACGATTGCCGCGCCGCCGCCCGCGCCGCGAGTCAGTGCGGTCCGAAAGAGGCTGATATCAGCGGCTCTTGCATTGGAACCGGATGAGTTAGCAGCACGCTTGCGGCCGCTCACGATCAGTTCATCACCCGCTGCAATGCAGAATCGATTTTCTCAAAACGAACGCATTTATGTTGCGACTTCGTCAGAGTTCCGAGTGTATAGTTTGGGCAACTTGAATCTCAGAGGAGGTCACGATGCCAGCACTCGCTGAAGTCCTGTCGACCAATATGCCTCGTCCCGCGCCGCGTGGAAGTGAGCTGCCGACTTGCCCGGTTTGTGCTGACTCGATGGTTGCCGCAGAAGCATCCGCCTTCATGACCGATAGCGTCGTCAGCTATCTGTGGACCTGTGATACTTGCGGTTACGGATTCGTAACCAAGCATTCGATGAAGCGCATCGTCTGCAGCTGATCGCGCACAGACCGCCCACTTTGTGTTCGATGGATCGGGCCCACGCACGGTCGTCGCTTTGCACTCAGCTAACCCGGCTTGGTGAGCTAGCCACCTAACGAAATCGCTAGCCTGGGTTAGCTCCCAAGCGGGACAAGATTTGGCATCAAGCGCAGCCCCGCCTGGGCTGAACCTGCCGGCCCAAACGCCCGGAAGCCAAGACACCCGGCAGTCAAGCGTTTGACCGCTCATTCTCCTGAGCAGATGTCCGGGCCCGGCTTTATCGATCGGCCCGTCGCAGCAGATAGACGTCCATGATCCAGCCGTGCCGCTGGCGCGCCTCCTGCCGTATCGTTGCGATCTTGTCCTTGACCTCGTCGAGTGGTCCGGCGATCAGAATTTCGTCGGGGGTCCCGAGATGGGCGCCCCAGAAGATCTCCAGATTTGCATCGCGCAGCCGGGCAAAGGCCTGGGTGCCGTCCAGCATCACCACCACGCTGCCGGCGTCATCCGGAAACCCCTCCGCGAGCTTGCGCCCGGTGGTCAACAGCACGGGTTCACCGATCTGGTTCAACGTAATCCGGTGCTTGGCGGCCAGCACCTGCACGCTGCTGATGCCGGGGATCACCTCATAGTCCAGCGCCAGACCCTTGGCGCGCACCCGCTCGATGATCCGCAGCGTACTGTCGTAAAGCGCGGGATCGCCCCACACCAACAGGCCTCCGACCTGACCATCCGAAAGGCACGCCTCGAACCTTTGCTGATACAGATCGGCAAGCTCCGCATGCCATCGATCGACATCGTCCTGATAATTGCCCGATGACGCCCGCTGCGGCACGTCGATCGCGACCGTGCGATAATCCGCGCGCTCGACGAAACGCTCGCAGATCGCGCTGCGCAGGTTTCGCAACGCGGCCTTCTCGGCGCCCTTGTCGGGAACGAAGAAGACGTCGACCCGATTCAAGGCCTTGACCGCCTGGATCGTCAGAAAGTCAGGATCGCCGGCTCCGATGCCGATCACCAGAATTTTTCGCATCGATTGGCCGTTCTGCCGCCCCGGCGCGGCGATTGCCGCGGCTCCGCTCCGAAAGCGGCGAAGACAGAGCATGGTCGGTCGCCGCACGCAAGCGCAGCCGCGCTATCCGATCGTCGGACGCAGCGCGCCTTGCCGCGCGGTTGACAATGCAAGGCCGCCGCTCCACTCAGTGCGGCGATCGTCCCCTAACACCAATGTGGTCCCGACATGATCGATCGAACGCGATCATGAGCACCGTGTCCGCCTCGACCAAGATCGATGTGCTGGTGGTCGGTGGCGGCAGCGCGGCCTTGTGTGCCGCCATCGCGGCGCGACGCCACGGCGCCACGGTGCGCCTGGTCGAACACGCGCCGTTGAGCCTGCGCGGCGGCAACACCCGCCACGCCCGCAATTTCCGCCTGATGCATGACACCGCGCATTGCTACGTCCCGGACAGCTATGGCGAAGACGCGTTCATGAACGATCTTCACCGCGTCACAAGGGGCGCGACCGACGCGACGCTGGCGCGTGTGCTGATTCGCGGCTCAGCGACGATCGCTCCCTGGCTGCAGGCCAATGGCGTGGCATTGCAGGATCCAGGCTGCGGCGTGATGCCTTATTCGCAGCGCACCGCATTTTTTCTCGGTGGCGGCAAGACGATGATCAATGCGCTCTATGCCACAGCCGCCAGGATCGGCATCGAGATCTGCTATGACAGTGAGGTCGTGGCTTTGCCGACCAGCGATGGCCAAGGCGGGAACGTGGTGATCGATCGAGGCGGCATCACCGAACTGGTGAGCCCGAAGGCGCTCGTGCTGTGCTGCGGCGGCCATCAATCCGATCGCGCCTGGTTGCGCGACAGCTTCGGCGACGCCGCCGACGGGCTGGTGGTCCGCGGAACGCCCTATGCCACCGGACGGGTGCTGCGGATGCTTCTCGATGCCGGCGCCAGGCCGGTCGGCGATCCGTCGCAAGGCCACATCGTTGCGGTCGATGCCCGCGGTCCGCCGGTCGACGGCGGCATCGTCACCCGCATCACCGCGATCCCTTCCGGCATCGTGGTCGACCGCAACGCTCAGCGCTTCCACGACGAGGGCGAGGACGCGCGCAAGACGCATTATGCCCGCTGGGGCGAGCGGATCGCGCAATGCCCCGGCCAGATCGCCTATCTGATTATGGACGCCCATGGCCGGGCGCGGGCGCTGCCGACAGCGCTGCCGCCGATCGAGGCCGATTCCATCGCGGCGCTGGCGGTCAAGCTCGGGCTCGACCCGGCAGCGCTGGAAGCCACGACGCGCGGCTTCAACGCCGCGATCGCCGGCGGCGAATTAATCCAACGGCGCACCGCACAGTTGGCGCCGGCGAAATCGCATGGCGCGGTCGCGCTCGCGGTGCCGCCCTTCGCGGCCTACCCGATGCGACCGGGCCTGACCTTCACCCATTTCGGCGTCGCCGTCGATCCGCAGATGCGGGTGATCAAATCCGACGGCAGCCGTTTCGAGAACATCTTCGCGGCCGGCATGATCATGGCGGCGAATGTGCTCGGCCGCGGCTATCTGGCCGGCCTCGGCGTCACATTGTCGGCGGTGTTCGGACGCCTCGCCGGCGAGGAGGCCGCGCGTCATGCCGCCCGATGACCTGGAAGCCGAGCGGGTGCTGCGAATCTGCACCGCCTGCATGTATTGCGACGGCTTGTGCGCGGTGTTTCCGGCGATCGCCGGCAAGCATGATTTCGCGCCCAACGACCTCACCTATCTGGCCAATCTGTGCCACAACTGCCGTGGCTGCTGGTACGCCTGCCAATACGCGCCGCCGCATCATTTCGCGATCAACCTGCCGAACACGCTGGCCGAATTGCGCCAGCGCTCCTATGCCGACTACGCTTGGCCGCGCTGGCTGGGTCGTGGCTTTGGCGCCAATGCCCGCGTGGTCGCCGCCATCGTCGGCGGCATCACCGCGTCGATGCTGATCGCCACGCTGCTGCTGGTGCCGGCCAATGTGCTGTTTGCCGCCCATCACGGCCCGGGCGCATTCTATCGGGTGGTGCCGTGGCCGATCATGGCCGGGGCCGCCGCGGCGACGCTGCTGTCGGCGATGCTGGCGATCGGCATCAGCGCGGCAAGCTATTGGCGCGCGATCACCCCCCGCGCCGGGACCAAGGCCATCTTGCGCGCGCTGTATCCCGCGGTGCTGGATATCGTAACGCTGCGCAATCTCGGCGGCGGCGGCCCCGGTTGCAACGACGCCGACGAGAAATTCTCCCAGCAACGCCGATGGTTTCACCACGTGATGGTGGCGGGCTTCGCGTTCAGCCTCGCCGCGACGCTGATCGCGGCATTCTATCATCACGTCTACGCCGTCGCGGCGCCCTACTCCTTGACCAGCCTGCCGGTGCTGGCCGGTGGCATCGGTGGGGTGACGATGCTGATCGGGATCGGCGGGCTGTTGCTGCTGGAACGGCGCGCCGACCGCGCCCTCTCCGCCGCCGCCGAGATTCGGCTTAACATCGTGTTCCTGGTCCTGCTCGCTTTGGTGGCCGGGAGCGGCCTTGCGGTGCTGGCGCTGCGCGAGACCGCGGCGATGGGGCTGGTGCTGACGCTGCATCTGGGCATCGTGATCGGCTTCTTCGCCATCCTGCCGGTCAGCAAGGCGGTCCACGGGTTGTATCGATCGCTGGCGCTGCTACGCGCCGCGATCGAGCGCGCGCGCCCGCGACGCAGCGGCGACGAGTGACATCGGTGCAGCCGCAGGACCATCGGGCGCAAGCCGCGGCCGATCGCGCCGTGTGGAGGATTGACTTCCCGGCGTTTCCGTCAGATTGAACCCGCAGCCGATGGTGCCTTGTCTGCGGACAGGGCGAAAAGGGAATACCGGGTGTCAGGATACGGCAAGTTGCCGGATCCGGACCAAGCCGGAGCTGCCCCCGCAACTGTGAGCGGAAAGCCTGCACCGAAAACCACTGGGTCTCGACCTGGGAAGGTGGTGCCGGCGATGACCCGCAAGCCAGGAAACCTGCCGTCGCCTGCTTTGTTCGCCATTCCGGGCGGGGTGTTTCGGAGTGAAGACGTTGGTCGATCGGAGTGCAGGTCCGCTCGCCGCATGTCTGGGTCTCGCGCTTTGCGCGGCCCATCCGGCGACGAGGCTTGCCTATGGATCACTGCGATCAACACGCGCCTGGCCAGGCGCCAGCGGCCAACTTAGTCGAGCGAACGGTCTCGCCGCGGCCCGGCCTCGAGCAATCCGCCGCCGAACTCGTGGTGCTGTCCTTTGCCGACGATGACCTCGCCGCTTTCGCGGCAGCATCGCGCGCGGCTGATGGCTTGCCGCGCCTGCATCTGGCCAATCTGCGCGATCTCGTCGATCCGCATGCGCGCGAGCCGCTGATCGCGACCACGCTGGCGCAGGCCCGCGGAATTCTGATCCGGCTGGGCGGCGGCCTGCCCTGGCCTGACGCCGTCGCGCGGGTCGCCGCGATGGCCGCCGCCAAGGGCATCGCGCTGGCGATCGTTCCGGGCGATGGCCAGGTCGATCCGCAATGCGACGCGGCCTCCAACCTGCCGCCCTCGACGCTGCGCCGGTTGAAAGCCCTGTGCGACAAGCCCGGTCCGGACTCAGCCCGCGCGGCGCTGGTCCAGCTGGCATTGGCCTCCGGTCTGCGAGCAGCGCCGCTCACCCACGCCACGCTGCCGCCCAGCATCGCCCCGACACCGACCCATTCCGAGGCCGCCTCATGAGCTACGTCTACGAGAAAAACGGCGCCGCGATCTACGCGCGCTCCTTCGCCATCATCCGCGCCGAGGCCAGGCTCGACCGCTTCGATGCCGCCGACGAGAAAGTCGCGGTCCGGATCATCCACGCCAGCGGCATGGTCGAGGTCGCCGACGACATCGTCTTCACCGGGGGCTTCAGTGTGGCCGCGGCGCATGCGTTGCGCGCCGGCGCGCCGATCCTGTGCGACGCCCAGATGGTCGCCAACGGCATCACCCGGGCGCGGTTGCCGGCCGATAACGAGGTGATCTGCACATTGAGCGATCCGCGCATTCCAGCACTGGCGGCGCGGCTTGGCACCACGCGGACCGCCGCGGCGATCGAATTGTGGCGCGACCGACTGGCCGGCGCCGTGGTGGTGATCGGCAACGCGCCGACCGCCCTGTTCCGGCTGCTGGAGATCCTGCAGGAGCCGGGCGTGGCCCCGCCGGCCGCGGTGATCGGCATTCCGGTCGGCTTCGTCGGCGCCGCCGAATCCAAGGACGCGCTGCTCGACTACGCCCTGGTGCCGAGCGTGATCGTGCGCGGACGGCGCGGCGGCAGCGCGATGGCGGCCGCCGCCGTCAACGCTGTGGCGAGTGACATCGAATGAGCCGCGCCGCGACGATCTATGGCGTCGGGCTCGGCCCCGGCGATCCCGAGCTGATGAGCGTCAAGGCGGCGCGGCTGATCGGCCAAGCCCGCGTCATCGCGCATTTCCGCAAACCCGGCCGCGCCGGCAATGCTCGTAGTTTGGTGGAAGGCATGCTCGCGCCCGGTGTGGTCGAGGAAGCGATGGAATATCCGGTCACCACCGAAATCGCGGTCGATGACCCCGCCTATAATGCCTGCCTACGCGATTTCTACAACGGCTGCGTCAAACGGCTTCTCGGTCATGTCGACGACGGCCGCGACGTCGCGGTGCTGTGCGAGGGCGATCCGTTTCTCTATGGCTCGTTCATGCATCTGCACAGCCGGCTCAAAGGCCAAGCCAAGGTCGTGGTGGTGCCGGGGATTTCCGGGATGTCGGGCTGCTGGACCGCCAGCGACATGCCGATCACCTTCGGCGACGACGTGTTGAGCGTGGTGCCGGCAACGCTCGACGAGGCCAGCTTGCGCGAACGCTTCGCTGGTGTAGATGCGCTGGTGGTGATGAAGCTCGGCCGCAATCTGCCGAAAGTGCGCCGCGCGCTGGATCATGCCGGGCTCACCGAGCGCGCGGTCTATGTCGAGCGTGGCACCATGGCCGAGCAGAAGGTGATGCGGCTGGCCGACAAGACCGACGACGAGGCGCCCTACTTCTCGGTGATCCTGGTCCATGGCCAAGGACGACGGCCATGAGCGGATCGCTGATCATCGCTGGCCTCGGGCCCGGCGCCGCCGATCTTGTGACCCCGGAAGTCACCGCCGCGCTGGCCCAGGCCACCGATCTGATCGGCTACGCGCCCTATGTGGCCCGCGTCGCCGAGCGGCCCGGCCTCACCCGTCACGGCTCCGACAATCGTCAAGAGCTCGACCGCGCCGGGCACGCGCTGCGGCTGGCCGCGCAAGGCAGGCGCGTCGTCGTGGTGTCGTCGGGCGATCCCGGCGTATTCGCGATGGCGGCGGCGGTGTTCGAAGCGGTCGATGCCGGCGATCCGTCATGGCGCGAGCTTGATATCAGAGTATTGCCCGGCATCAGCGCGATGTTCGCGGCCGCAGCGCGGATCGGCGCGCCGCTCGGCCACGATTTCTGTGCGATCAATCTGTCGGATAATCTGAAGCCGTGGCAGCTGGTGGAGCGTCGGCTGCGGCTGGCGGCCCAGGCCGATTTCGTCATCGCGCTGTATAACCCGCTGTCGAAGGCGCGGCCATGGCAGCTCGGCCGTGCGCTCGACTTGCTGCGCGGGGAATTGCCAGGCCACGTGCCGGTGATCTTCGCCAGCGCCATCAGCGACGCCAGGGAGGCGATCGACACTGTATCGCTCGCTGAGGCGGCGGCAGAGCGCGCCGACATGCGCACGCTGGTGATGATCGGATCAACCCAGACCAGGCTGATCGAACGCGGCAACGGCAAGCCGTTCGTCTACACGCCGCGTTCCGTTGGAGTGGCATCGTGACCGAGCCAGCGCAGCACCGCGGCGACGGAATCGACCACCTCGCGCGCCGGAACGTAAGGTCGCCGCACCATCACCACCGGCAGAGCCAGATCGCGCGCGGCCTCGATCTTGGCCGAGGCGGCATCGCCGCCGGCATTTTTCGCGACGATGAGATCAGCGCGAAACTCTGTCAGCATGGCGCGATCGGCGGCGCGCGCGAACGGCCCGCGCGCCACGATCACTTCGGCATTGGGCAGCGGCAGCGGCGCGAGCGGCGTATCGACCAGCCGCACCAGATAAGCGTGCTGCGGATGCGCGGCGAAGATGTTCAGATGCATCCGGCCGATGCCGAGAAAAACCCGGCGCGGCGCGGCGCCGATTGCGACGGCTGCGGCATCGAGATCGTCAACCTCGATCCAGCGATCGCCGCTTTGGCGCTGCCATGGCGCCCGCTCGAGCGCCAGCAGCGGCACCCCCGCCCGCTCGCAGGCAGCGACCGCATGCGCGCTCATCTGCGCCGCGAACGGATGGGTGGCATCGACGACGCGGCCGATCCGCTGCGCACGCAGATAGTCG"

cat(">contig1\n",initialseq, "\n", sep="", file="test_genome.fa")

fastqq=c("?","@","A","B","C","D","E","F","G","H","I")

pi=95 #% identity

compare=FALSE
min_rz=100
Read_size_i=150
for (x in 1:7) {
sample=paste("Sample",x, sep="")
cat("\nCreating sample:", sample, "\n", file="Create_reads.log", append = TRUE)
  step_nc=as.integer(x*100/(100-pi))
  newgno=modify_genome_inblocks(initialseq,pi,step_nc)#so we get reads 95% identity regardless the read size - x change every X*20 nucleotides
  cat(">contig1\n",initialseq, "\n", sep="", file=paste(sample,"test_modf_genome.fa", sep="_"))
    if (x >  1) {
    m=1
    while (m<min_rz) {
    prz=m*step_nc
    if (prz >= min_rz) {
      Read_size=prz
      m=min_rz} else {m=m+1}
    }
    
  } else { Read_size=Read_size_i }
  
  Readsg=shotreads(newgno,Read_size)
  totalNreads=length(Readsg)
  counter=1
  
  for (r in Readsg){
    qual=""
    for (q in sample(fastqq,Read_size, replace = TRUE)) { qual=paste(qual,q, sep="") } 

    cat("@MLtest:C2N1TACXX:6:2301:9088:",counter,"/1\n", r, "\n+\n", qual,"\n", sep="", file=paste(sample, "R1.fq", sep="_"), append = TRUE)
    revread=revcompl(r)
    cat("@MLtest:C2N1TACXX:6:2301:9088:",counter,"/2\n", revread, "\n+\n", qual, "\n", sep="", file=paste(sample, "R2.fq", sep="_"), append = TRUE)
    counter=counter +1
  }
  gzip(paste(sample, "R1.fq", sep="_"))
  gzip(paste(sample, "R2.fq", sep="_"))
    cat("Total number of reads generated at", pi, "% identity :", totalNreads, "\n", file="Create_reads.log", append = TRUE)
}



#for (Read_size in c(100,120,150)) {
for (Read_size in c(150)) {
  x=x+1
  sample=paste("Sample",x, sep="")
  cat("\nCreating sample:", sample, "\n", file="Create_reads.log", append = TRUE)

newgno=modify_genome_inblocks(initialseq,pi,Read_size) #so we get reads 95% identity - 5 change every 100 nucleotides/6 change every 120 nucleotides/7 change every 150 nucleotides
cat(">contig1\n",initialseq, "\n", sep="", file=paste(sample,"test_modf_genome.fa", sep="_"))
Readsg=shotreads(newgno,Read_size)
totalNreads=length(Readsg)
counter=1
for (r in Readsg){
  qual=""
  for (q in sample(fastqq,Read_size, replace = TRUE)) { qual=paste(qual,q, sep="") } 
  cat("@MLtest:C2N1TACXX:6:2301:9088:",counter,"/1\n", r, "\n+\n", qual,"\n", sep="", file=paste(sample, "R1.fq", sep="_"), append = TRUE)
  revread=revcompl(r)
  cat("@MLtest:C2N1TACXX:6:2301:9088:",counter,"/2\n", revread, "\n+\n", qual, "\n", sep="", file=paste(sample, "R2.fq", sep="_"), append = TRUE)
  counter=counter +1
}
gzip(paste(sample, "R1.fq", sep="_"))
gzip(paste(sample, "R2.fq", sep="_"))
cat("Total number of reads generated at", pi, "% identity :", totalNreads, "\n",  file="Create_reads.log", append = TRUE)
}


#comparando
if (compare==TRUE) {
  Reads=shotreads(initialseq,Read_size)
  for (y in 1:length(Reads)) {
    print(Reads[[y]])
    print(Readsg[[y]])
    cat("\n")
  }
}




##############################################################
#Method 1 modification on Reads _ With this method I can evaluate mapping software bu I cannot generate VCF files
#create_reads<-function(iseq, pid,jump) {
#tosplit=as.list(strsplit(iseq,""))[[1]]
#NumReads=0
#step=100-pid-1
#
#for (r in seq(1,length(tosplit)-step,jump)) {
#  read=""
#  if ( r > step & step > -1) {
#    start=tosplit[seq(1,r-1)]
#    for(s in start) { read=paste(read,s,sep="") }
#  }
#  if (step > -1) { 
#    Q=tosplit[seq(r,r+step)]
#    newseq=modify_seq(Q)
#    
#    for(n in newseq) { read=paste(read,n,sep="") }
#  }
#  end=tosplit[seq(r+step+1,length(tosplit))]
#  if (r < length(tosplit)-step) for(u in end) { read=paste(read,u,sep="") }
#  NumReads=NumReads+1
#  
#  print(read)
#  revread=revcompl(read)
#  print(revread)
#  cat("\n")
#}  
#return(NumReads)
#}


#Reads=shotreads(initialseq,150)
#totalNreads=0
#for (r in Reads){ totalNreads=totalNreads+create_reads(r, pi,150) }
#cat("Total number of reads generated at", pi, "% identity :", totalNreads, "\n")

#Method 2 Modification on genome - Here I can evaluate mappng software and generate VCF files
#modify_genome<-function(mys,pi,ecarts){
#secuen=as.list(strsplit(mys,""))[[1]]
#sizeseq=length(secuen)
#cat("Original Sequence size:", sizeseq, "\n")
##ecarts=sizeseq/Nofsites
#modiread=""
#for (e in seq(1,sizeseq-ecarts+1, ecarts)) {
#  start=secuen[seq(e,e+ecarts-1-(100-pi))]
#  for (s in start) {modiread=paste(modiread,s,sep="")}
#  q=secuen[seq(e+ecarts-(100-pi),e+ecarts-1)]
#  final=e+ecarts-1
#  new=modify_seq(q)
#  for (n in new) {modiread=paste(modiread,n,sep="")} 
#  
#}  
#if (final < sizeseq) {
#  end=secuen[seq(final+1,sizeseq)]
#  for (f in end) {modiread=paste(modiread,f,sep="")}
#}
#return(modiread)
#}
#Read_size=150
#newgno=modify_genome(initialseq,99,100/(100-pi)) #so we get reads 95% identity  - option2 - no matter the read size
#Readsg=shotreads(newgno,Read_size)
#totalNreads=length(Readsg)
#counter=1
#print("Sample1")
#for (r in Readsg){
#  qual=""
#  for (q in sample(fastqq,Read_size, replace = TRUE)) { qual=paste(qual,q, sep="") } 
#  cat("@ML_test:fwread:",counter,"\n", r, "\n+\n", qual,"\n", sep="", file="sample1_R1.fq", append = TRUE)
#
#  revread=revcompl(r)
#  cat("@ML_test:revread:",counter,"\n", revread, "\n+\n", qual, "\n", sep="", file="sample1_R2.fq", append = TRUE)
#  counter=counter +1
#}
#cat("Total number of reads generated at", pi, "% identity :", totalNreads, "\n")


#Read_size=150
#newgno=modify_genome_inblocks(initialseq,pi,100/(100-pi)) #so we get reads 95% identity regardless the read size - one change every 20 nucleotides
#Readsg=shotreads(newgno,Read_size)
#totalNreads=length(Readsg)
#counter=1
#print("Sample2")
#for (r in Readsg){
#  qual=""
#  for (q in sample(fastqq,Read_size, replace = TRUE)) { qual=paste(qual,q, sep="") } 
#  cat("@ML_test:fwread:",counter,"\n", r, "\n+\n", qual,"\n", sep="", file="sample2_R1.fq", append = TRUE)
#  
#  revread=revcompl(r)
#  cat("@ML_test:revread:",counter,"\n", revread, "\n+\n", qual, "\n", sep="", file="sample2_R2.fq", append = TRUE)
#  counter=counter +1
#}
#cat("Total number of reads generated at", pi, "% identity :", totalNreads, "\n")
